"""add_is_paid_to_appointment

Revision ID: 97dba8891ee4
Revises: fed3dd2719a2
Create Date: 2026-02-05 14:05:09.413181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97dba8891ee4'
down_revision: Union[str, Sequence[str], None] = 'fed3dd2719a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('appointment', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'is_paid')
    # ### end Alembic commands ###
