"""add_confirmation_tracking

Revision ID: cfff72963153
Revises: 151cc8e88230
Create Date: 2026-02-11 12:51:28.099893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfff72963153'
down_revision: Union[str, Sequence[str], None] = '151cc8e88230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('confirmation_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'confirmation_sent_at')
    # ### end Alembic commands ###
